### ISSUE TITLE
[FEATURE_REQUEST] acot can't audit sites that return 404 responses to HEAD requests

### ISSUE THREAD

**Issue by odanado** [acot-a11y/acot#34]
## Is your feature request related to a problem? Please describe.

By default, https://github.com/jeffbski/wait-on waits for a 2xx response to HEAD requests.
Some HTTP servers do not implement the HEAD method and may return a 404 response.

e.g. https://mdn.mozillademos.org/ja/docs/Web/CSS/:focus$samples/Example

## Describe the solution you'd like

acot uses `http-get` instead of `http` to wait
ref: https://github.com/jeffbski/wait-on/blob/546f1bffde125af8aef5ff196aca8454726b21c7/lib/wait-on.js#L63-L66

## Describe alternatives you've considered
Change to another library.

## Additional context
To use the GET method for wait-on, I need to put `origin: 'http-get://localhost:8080'` in acot.config.js, but this is not a legal URL.

**Comment by wadackel** [comment]
Hi @odanado, Thank you for feature request.

I agree with forcing the `GET` request :+1:
After changing the behavior of acot, I will release it as canary first.

**Comment by wadackel** [comment]
Released as `@acot/cli@0.0.6-canary.0`.
