### ISSUE TITLE
[BUG] Failed to run `init` and `run` because did'nt install 'acot@latest'

### ISSUE THREAD

**Issue by YusukeHirao** [acot-a11y/acot#91]
## Describe the bug

I had run the command `npx acot init`. Then it failed to run with throwing the below error.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/acot - Not found
npm ERR! 404 
npm ERR! 404  'acot@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I run  `npx acot run`  but it failed too.

## Environment

- OS: macOS 10.15.7
- node: v14.16.0
- npm: v7.6.3

**Comment by YusukeHirao** [comment]
Oh, sorry I was getting ahead of myself. I thought that it doesn't need to install '@acot/core' and it installs that automatically.

I think it should install that automatically just like installing "@acot/acot-config".
What do you think?

**Comment by wadackel** [comment]
Hi @YusukeHirao, Thank you for reporting :dog: :heart:

Would you tell me more about the steps to reproduce the error?
Thanks.

**Comment by YusukeHirao** [comment]
@wadackel 
OK, Of course.

1. Make a directory.
2. Change the current directory.
3. The directory is just empty.
4. Execute `npx acot init`, without before execute `npm install @acot/core`.
5. The error is thrown.

**Comment by wadackel** [comment]
@YusukeHirao 

Thank you for the steps to reproduce :+1:

Did you install `@acot/cli` before running `npx acot init` command?

Since npx has the ability to run the locally installed `node_modules/.bin`, Getting Started takes advantage of that feature.
https://github.com/acot-a11y/acot#getting-started

**Comment by YusukeHirao** [comment]
@wadackel 

Umm, I'm sorry.
Actually, that was my misunderstanding.

I understood, so I close this issue.
Thank you!

**Comment by wadackel** [comment]
Don't worry about it :dog:
Thank you for contributing.
